### ISSUE TITLE
npm安装非常慢

### ISSUE THREAD

**Issue by luozhou7dev** [Chimeejs/chimee-player#14]
拉其他依赖没问题 但是拉chimee-player就一直卡在checking installable status

**Comment by toxic-johann** [comment]
什么源？

**Comment by dmh19900611** [comment]
⸨░░░░░░░░░░░░░░░░░░⸩ ⠋ fetchMetadata: sill resolveWithNewModule chimee-player@1.4.7 checking installable status

淘宝和npmjs 是一样的都卡住。可以快点解决吗。。疯了

**Comment by dmh19900611** [comment]
翻了墙。国外的慢至少能装，淘宝的，直接报错

**Comment by toxic-johann** [comment]
大家重新下载试试，应该 1.4.8 修复了

**Comment by anrananran** [comment]
为什么安装依赖非得走 https://github.com/Chimeejs/chimee-helper/tarball/master ，太慢了
