### ISSUE TITLE
好像也没有解决播放器在不同手机浏览器的H5页面中的UI样式问题吧？

### ISSUE THREAD

**Issue by hauk0101** [Chimeejs/chimee-player#19]
本人也有在做网页播放器的相关业务工作，遇到最头疼的莫过于国产手机浏览器厂商，对 video 标签的劫持问题，基本上自己写的 video 相关的控制栏样式完全没有什么意义，会被不同的手机浏览器做不同的样式展示，不知道 chimee-player 在做H5播放器的 UI 时，做到了哪一步，有没有什么解决方案呢？

**Comment by toxic-johann** [comment]
除了x5, uc 系这种会提供部分接口的。其余我们目前也没什么办法。
