### ISSUE TITLE
m3u8 格式有的播放不了

### ISSUE THREAD

**Issue by qq1157918444** [Chimeejs/chimee-player#21]
报错：vendor.1fd61b8e0a1f3bc4b8db.js:72323 [chimee-kernel-hls hlsError] > bufferSeekOverHole
有的都能播放，有的只有音频，没有视频，有的音频和视频都没有，这是咋回事呢？谢谢！

**Comment by toxic-johann** [comment]
流的问题，使用 hls.js 调试下。
