### ISSUE TITLE
打包后名字修改

### ISSUE THREAD

**Issue by lizheming** [Chimeejs/chimee-player#3]
https://cdn.baomitu.com/chimee-player 现在叫 `index.browser.js` 有点不好看，推荐改成 `chimee.js` 之类的正常一点的名字。

![image](https://user-images.githubusercontent.com/424491/32585910-b0721f16-c53a-11e7-83a1-83b8ad374e5e.png)

**Comment by huzunjie** [comment]
这个可以有，后续版本里我改一下

**Comment by toxic-johann** [comment]
@lizheming 顺拜问问 chimee 会加上吗？如果加上我也改一下。

**Comment by lizheming** [comment]
@toxic-johann 之前问好像说只要 chimee-player 就好了？如果 umd 单独引用 chimee 没问题的话也可以加上去。chimee 这个 repo 已经过了 cdnjs 的 pr 条件了，如果提交可以直接提交给 github.com/cdnjs/cdnjs 仓库

**Comment by toxic-johann** [comment]
chimee 的 browser 也是可以单独引用的。我改好知会你一声。

**Comment by lizheming** [comment]
那你们是不是确认下单独引用的版本到底是 chimee 还是 chimee-player ？仓库的名字太相似如果并存的话很容易让人困惑，或者说改个更明显的名字？

**Comment by toxic-johann** [comment]
chimee 只是一个框架，chimee-player 是什么都有。不过确实有可能误认。。。我门考虑一下

**Comment by lizheming** [comment]
嗯，个人建议如果两者都能用还是推一个在浏览器单独引用情况下使用方便的 repo 来推即可。

**Comment by huzunjie** [comment]
我会改名index为chimee-player，两者最大区别：chimee-player 是一个可以直接上手用的包，不用太关注一些内在实现，了解基本的入口API就可以，新用户更容易入门一些；chimee 更适合进阶用户，在自己业务场景中要做一些深层次的定制化开发的群体。
