### ISSUE TITLE
移动端ios,视频加载失败

### ISSUE THREAD

**Issue by londen** [Chimeejs/chimee-player#4]
![wechatimg29](https://user-images.githubusercontent.com/13990799/33654597-93c31844-daab-11e7-9589-eb3e2b572b01.jpeg)

一直都是loading状态，然后就加载失败了，有时候这里
<img width="324" alt="wx20171206-173411 2x" src="https://user-images.githubusercontent.com/13990799/33654652-b91f680e-daab-11e7-9f40-c666131a200f.png">
切换一下就能显示视频了。什么原因造成的呢？我引用的是chimee-player.browser.js这个版本的。

**Comment by huzunjie** [comment]
移动端 ios 不允许Video自动播放，如果有移动端应用需求可以参考移动版： https://github.com/Chimeejs/chimee-plugin-mobile-controlbar/tree/master/demo

**Comment by londen** [comment]
https://github.com/Chimeejs/chimee-plugin-mobile-controlbar/tree/master/demo  这个我下载下来跑在服务下报错。
<img width="1037" alt="wx20171206-183917 2x" src="https://user-images.githubusercontent.com/13990799/33657716-16a29b32-dab5-11e7-82d4-9daa82d95a4c.png">

**Comment by yandeqiang** [comment]
chimee 是 node_modules 里的文件， 你先 npm 一下

**Comment by londen** [comment]
<script src="../node_modules/chimee/lib/index.browser.js"></script>
<script src="../lib/index.browser.js"></script>
你这里引用了2个index.browser是什么意思？

**Comment by yandeqiang** [comment]
一个是这个 chimee 。 一个是这个控制条




| |
耳机静世界
|
|
邮箱：18636404184@163.com
|

签名由 网易邮箱大师 定制

在2017年12月06日 19:30，londen 写道：
<script src="../node_modules/chimee/lib/index.browser.js"></script> <script src="../lib/index.browser.js"></script>

你这里引用了2个index.browser是什么意思？

**Comment by londen** [comment]
如果我不用node之类的仅仅是把"../node_modules/chimee/lib/index.browser.js"这个js文件引入可以吗？我自己本地测试了一下，在手机上框子能出来但是没办法播放视频
