### ISSUE TITLE
播放m3u8文件时报错

### ISSUE THREAD

**Issue by tracerZzz** [Chimeejs/chimee-player#5]
![image](https://user-images.githubusercontent.com/13192550/34664389-9e1e6b68-f496-11e7-9d90-20140209de5a.png)
代码拷贝自github readMe 文档，只是改了一下src属性的url

**Comment by huzunjie** [comment]
@tracerZzz 麻烦给个demo或者详细点的代码参考判断一下..

**Comment by tracerZzz** [comment]
已经解决了，我换了个webpack的环境就好了，可能是我之前的webpack打包出现问题
